default: help

# Show help
help:
    @just --list

# ==== codebase ====

# Format using ruff format
[group('codebase')]
ruff:
    uv run ruff format
    uv run ruff check --fix

# Lint using ty check
[group('codebase')]
ty:
    uv run ty check
